from .map_brownlands import *
from .map_eriador import *
from .map_gondor_rohan import *
from .map_misty_mountains import *
from .map_mordor import *
from .map_wilderland import *

territory_list = (
    wold,
    east_emnet,
    west_emnet,
    anorien,
    nindalf,
    dead_marshes,
    noman_lands,
    emyn_muil,
    brown_lands,
    harlindon,
    forlindon,
    ered_luin,
    mithlond,
    emyn_beraid,
    shire,
    sarn_ford,
    barrow_downs,
    bree_land,
    weather_hills,
    south_downs,
    north_downs,
    emyn_uial,
    carn_dum,
    ettenmoors,
    druwaith_iaur,
    anfalas,
    ras_morthil_andrast,
    pinnath_gelin,
    lamedon,
    dol_amroth,
    belfalas,
    dor_en_ernil,
    lebennin,
    south_ithilien,
    pelennor,
    harondor,
    north_ithilien,
    gap_of_rohan,
    westfold,
    eastfold,
    northern_waste,
    mount_gundabad,
    ered_mithrin,
    hithaeglir,
    rhudaur,
    rivendell,
    carrock,
    loeg_ningloron,
    eregion,
    moria,
    enedwaith,
    lorien,
    parth_celebrant,
    fangorn,
    methedras,
    nan_curunir,
    udun,
    gorgoroth,
    morgul_vale,
    nurn,
    lithlad,
    khand,
    near_harad,
    far_harad,
    umbar,
    haradwaith,
    withered_heath,
    erebor,
    dale,
    esgaroth,
    woodland_realm,
    emyn_nu_fuin,
    mirkwood,
    dol_guldur,
    east_bight,
    dorwinion,
    rhun,
    iron_hills,
)
